
<EmailPasswordVerifyScreen>
	auto_dismiss: False
	size_hint: .7, .3
	title: "Email and Password Verification"
	FloatLayout:
		canvas.before:
			Color: 
				rgba: 213/255, 212/255, 212/255, 1
			Rectangle:
				pos: self.pos
				size: self.size
		Label:
			text: root.screenMessage
			size_hint: (.2, .15)
			pos_hint: {"center_x": .5, "center_y": .7}
			color: 0, 0, 0, 1
		Button:
			text: "Confirm"
			size_hint: (.2, .15)
			pos_hint: {"center_x": .5, "y": .1}
			on_release: root.dismiss()